# **Diplomado en Inteligencia Artificial y Aprendizaje Profundo**

#**Numpy**

*   ¿Qué es Numpy?

NumPy es una librería Python open source que introduce los vectores y las matrices en Python. Posee numerosas funciones para trabajar con dichos vectores y matrices.

¿Por qué usar arrays de numpy y no listas o tuplas de python?

Aunque python base tiene listas, el usar arrays es más rápido y consume menos memoria. Algo altamente necesario cuando se hacen operaciones de gran tamaño como puede ser el algebra matricial, por ejemplo.

# **Creación básica de arrays**

A continuacion se presenta un ejemplo de la creación arrays de distintas dimensiones. Para esto podemos usar números, listas o tuplas.

In [ ]:

#Manejo de conjuntos o 'arrays'

#librerias
import numpy as np

In [ ]:
#Creación básica de arrays
a=np.array(13) #array de dimensión 0
b=np.array([1,2,3,4]) #array de dimensión 1
c=np.array([[1,2,3,4],[5,6,7,8]]) #array de dimensión 2
d=np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]]) #array de dimensión 3

print("a =",a,"\n")
print("b =",b,"\n")
print("c =",c,"\n")
print("d =",d,"\n")

a = 13 

b = [1 2 3 4] 

c = [[1 2 3 4]
 [5 6 7 8]] 

d = [[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]] 



In [ ]:
#Dimensiones
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


# **Indexación básica**

In [ ]:
#Indexación
print("a =",a)
print("b[2] = ",b[2])
print("c[1] =",c[1])
print("d[1] =",d[1])

print("a =",a)
print("b[2] =",b[2])
print("c[1,2] =",c[1,2])
print("d[1,0,2] =",d[1,0,2])

a = 13
b[2] =  3
c[1] = [5 6 7 8]
d[1] = [[ 9 10 11 12]
 [13 14 15 16]]
a = 13
b[2] = 3
c[1,2] = 7
d[1,0,2] = 11


In [ ]:
#Segmentar arrays
print(b[1:4]) #b = [1 2 3 4] 
print(c[1,1:3]) #c = [[1 2 3 4][5 6 7 8]] 

[2 3 4]
[6 7]


#**Diferentes tipos de datos en los arrays**

In [ ]:
#Tipos de datos en los arrays
frutas = np.array(['Manzana', 'Naranja', 'Uva']) #cadenas
print(frutas)
print(frutas.dtype)

['Manzana' 'Naranja' 'Uva']
<U7


In [ ]:
#Manipulación de datos
number_to_string=np.array([6,1,2,4,623,8], dtype='S') #b denota un string
print(number_to_string.dtype)
print(number_to_string)

|S3
[b'6' b'1' b'2' b'4' b'623' b'8']


In [ ]:
try:
    error_array = np.array(['a', '2', '3'], dtype='i') #la a genera el error
except:
    print("hay un error en su lógica") 

hay un error en su lógica


In [ ]:
#Cambiar arrays ya existentes
floating_array = np.array([1.1, 2.1, 3.1]) #punto flotante

int_array = floating_array.astype('i')
print(int_array)

[1 2 3]


In [ ]:
#Forma de los arrays
#Numero de elemntos de la dimensión
print(a.shape) # a = 13 
print(b.shape) # b = [1 2 3 4] 
print(c.shape) # c = [[1 2 3 4][5 6 7 8]] 
print(d.shape) # d = [[[ 1  2  3  4][ 5  6  7  8]] [[ 9 10 11 12][13 14 15 16]]] 

()
(4,)
(2, 4)
(2, 2, 4)


In [ ]:
#Reformar arrays
#La reforma funciona siempre y cuando coincida con el número de elementos
print("c =",c,"\n")
c_1D=c.reshape(1,8)
print("c_1D =",c_1D,"\n")
c_4D=c.reshape(4,2)
print("c_4D =",c_4D,"\n")

c = [[1 2 3 4]
 [5 6 7 8]] 

c_1D = [[1 2 3 4 5 6 7 8]] 

c_4D = [[1 2]
 [3 4]
 [5 6]
 [7 8]] 



In [ ]:
#Dimensión desconocida
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr.reshape(3,-1)
d.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [ ]:
#Transpuesta
print("c =",c,"\n")
print("c.T =",c.T)

c = [[1 2 3 4]
 [5 6 7 8]] 

c.T = [[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [ ]:
#Iterar arrays
for x in d:
  print(x)

[[1 2 3 4]
 [5 6 7 8]]
[[ 9 10 11 12]
 [13 14 15 16]]


In [ ]:
#Iterar cada elemento por cada dimensión
#for no es optimo, usamos la función
for x in np.nditer(d):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16


In [ ]:
#Operaciones entre arrays
#Suma
#no.add() lo aplica entre argumentos
arr1=np.array([[1,2,3],
               [4,5,6]])
arr2=np.array([[6,5,4],
               [3,2,1]])
np.add(arr1,arr2)


array([[7, 7, 7],
       [7, 7, 7]])

In [ ]:
#np.sum() lo aplica a los elementos totales
arr3=np.array([[1,1,1],[1,1,1]])
print(np.sum([arr1,arr2]))
print(np.sum([arr1,arr2,arr3]))

42
48


In [ ]:
np.sum([arr1,arr2, arr3],axis=0)

array([[8, 8, 8],
       [8, 8, 8]])

In [ ]:
np.sum([arr1,arr2, arr3],axis=1)

array([[5, 7, 9],
       [9, 7, 5],
       [2, 2, 2]])

In [ ]:
#Multiplicación
print("arr1=\n",arr1,"\n")
print("arr2=\n",arr2,"\n")
print(np.prod([arr1,arr2]),"\n")
print(np.prod([arr1,arr2],axis=0),"\n")
print(np.prod([arr1,arr2],axis=1))

arr1=
 [[1 2 3]
 [4 5 6]] 

arr2=
 [[6 5 4]
 [3 2 1]] 

518400 

[[ 6 10 12]
 [12 10  6]] 

[[ 4 10 18]
 [18 10  4]]


In [ ]:
#Multiplicación matricial
np.matmul(arr1, arr2.T)

array([[28, 10],
       [73, 28]])

In [ ]:
#Multiplicación matricial
np.dot(arr1, arr2.T)

array([[28, 10],
       [73, 28]])

In [ ]:
print("d =\n",d,"\n") #2,2,4
print("d.reshape =\n",d.reshape(2,4,2),"\n") #2,4,2
np.dot(d,d.reshape(2,4,2)) #2,2,2,2

d =
 [[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]] 

d.reshape =
 [[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]] 



array([[[[ 50,  60],
         [130, 140]],

        [[114, 140],
         [322, 348]]],


       [[[178, 220],
         [514, 556]],

        [[242, 300],
         [706, 764]]]])

In [ ]:
print(np.dot(d[0],d.reshape(2,4,2)[0]),"\n")
print(np.dot(d[0],d.reshape(2,4,2)[1]),"\n")
print(np.dot(d[1],d.reshape(2,4,2)[0]),"\n")
print(np.dot(d[1],d.reshape(2,4,2)[1]),"\n")

[[ 50  60]
 [114 140]] 

[[130 140]
 [322 348]] 

[[178 220]
 [242 300]] 

[[514 556]
 [706 764]] 



In [ ]:
np.matmul(d,d.reshape(2,4,2))

array([[[ 50,  60],
        [114, 140]],

       [[514, 556],
        [706, 764]]])